package fr.graynaud.eu4saveeditor.common;

import fr.graynaud.eu4saveeditor.service.object.data.DataType;

public final class Keys {

    private Keys() {
    }

    public static DataType getTypeMeta(String key) {
        switch (key) {
            case "date":
                return DataType.DATE;

            case "save_game":
            case "player":
            case "displayed_country_name":
            case "campaign_id":
            case "checksum":
            case "name":
            case "key":
            case "selector":
            case "localization":
                return DataType.STRING;

            case "savegame_version":
                return DataType.OBJECT;

            case "first":
            case "second":
            case "third":
            case "forth":
            case "campaign_length":
            case "id":
            case "comparison":
            case "sample_count":
                return DataType.INT;

            case "slander_merchants":
                return DataType.FLOAT;

            case "savegame_versions":
            case "dlc_enabled":
            case "mod_enabled":
                return DataType.LIST_STRINGS;

            case "multi_player":
            case "not_observer":
                return DataType.BOOL;

            case "campaign_stats":
                return DataType.LIST_OBJECTS;

            default:
                System.out.println("Unknown meta key: " + key);
                return DataType.UNKNOWN; //If UNKNOWN, DataType.getType(value), mostly because a key can have multiple types (ex: value)
        }
    }

    public static DataType getTypeAi(String key) {
        switch (key) {
            case "start_date":
            case "end_date":
                return DataType.DATE;

            case "checksum":
                return DataType.STRING;

            case "king_data":
            case "ai_data":
            case "diplomatic_biases":
            case "target_unit_id":
            case "focal_point":
            case "country":
            case "ai":
            case "unit":
            case "REB":
            case "PIR":
            case "NAT":
            case "SWE":
            case "DAN":
            case "FIN":
            case "GOT":
            case "NOR":
            case "SHL":
            case "SCA":
            case "EST":
            case "LVA":
            case "SMI":
            case "KRL":
            case "ICE":
            case "ACH":
            case "ALB":
            case "ATH":
            case "BOS":
            case "BUL":
            case "BYZ":
            case "CEP":
            case "CRO":
            case "CRT":
            case "CYP":
            case "EPI":
            case "GRE":
            case "KNI":
            case "MOE":
            case "MOL":
            case "MON":
            case "NAX":
            case "RAG":
            case "RMN":
            case "SER":
            case "TRA":
            case "WAL":
            case "HUN":
            case "SLO":
            case "TUR":
            case "CNN":
            case "CRN":
            case "ENG":
            case "LEI":
            case "IRE":
            case "MNS":
            case "SCO":
            case "TYR":
            case "WLS":
            case "NOL":
            case "GBR":
            case "MTH":
            case "ULS":
            case "DMS":
            case "SLN":
            case "KID":
            case "HSC":
            case "ORD":
            case "TRY":
            case "FLY":
            case "MCM":
            case "KOI":
            case "LOI":
            case "BRZ":
            case "CAN":
            case "CHL":
            case "COL":
            case "HAT":
            case "LAP":
            case "LOU":
            case "MEX":
            case "PEU":
            case "PRG":
            case "QUE":
            case "CAM":
            case "USA":
            case "VNZ":
            case "AUS":
            case "CAL":
            case "TEX":
            case "DNZ":
            case "KRA":
            case "LIT":
            case "LIV":
            case "MAZ":
            case "POL":
            case "PRU":
            case "KUR":
            case "RIG":
            case "TEU":
            case "PLC":
            case "VOL":
            case "KIE":
            case "CHR":
            case "OKA":
            case "ALE":
            case "ALS":
            case "AMG":
            case "AUV":
            case "AVI":
            case "BOU":
            case "BRI":
            case "BUR":
            case "CHP":
            case "COR":
            case "DAU":
            case "FOI":
            case "FRA":
            case "GUY":
            case "NEV":
            case "NRM":
            case "ORL":
            case "PIC":
            case "PRO":
            case "SPI":
            case "TOU":
            case "BER":
            case "AAC":
            case "ANH":
            case "ANS":
            case "AUG":
            case "BAD":
            case "BAV":
            case "BOH":
            case "BRA":
            case "BRE":
            case "BRU":
            case "EFR":
            case "FRN":
            case "GER":
            case "HAB":
            case "HAM":
            case "HAN":
            case "HES":
            case "HLR":
            case "KLE":
            case "KOL":
            case "LAU":
            case "LOR":
            case "LUN":
            case "MAG":
            case "MAI":
            case "MEI":
            case "MKL":
            case "MUN":
            case "MVA":
            case "OLD":
            case "PAL":
            case "POM":
            case "SAX":
            case "SIL":
            case "SLZ":
            case "STY":
            case "SWI":
            case "THU":
            case "TIR":
            case "TRI":
            case "ULM":
            case "WBG":
            case "WES":
            case "WUR":
            case "NUM":
            case "MEM":
            case "VER":
            case "NSA":
            case "RVA":
            case "DTT":
            case "ARA":
            case "CAS":
            case "CAT":
            case "GRA":
            case "NAV":
            case "POR":
            case "SPA":
            case "GAL":
            case "LON":
            case "ADU":
            case "VAL":
            case "ASU":
            case "MJO":
            case "AQU":
            case "ETR":
            case "FER":
            case "GEN":
            case "ITA":
            case "MAN":
            case "MLO":
            case "MOD":
            case "NAP":
            case "PAP":
            case "PAR":
            case "PIS":
            case "SAR":
            case "SAV":
            case "SIC":
            case "SIE":
            case "TUS":
            case "URB":
            case "VEN":
            case "MFA":
            case "LUC":
            case "LAN":
            case "JAI":
            case "BRB":
            case "FLA":
            case "FRI":
            case "GEL":
            case "HAI":
            case "HOL":
            case "LIE":
            case "LUX":
            case "NED":
            case "UTR":
            case "ARM":
            case "AST":
            case "CRI":
            case "GEO":
            case "KAZ":
            case "MOS":
            case "NOV":
            case "PSK":
            case "QAS":
            case "RUS":
            case "RYA":
            case "TVE":
            case "UKR":
            case "YAR":
            case "ZAZ":
            case "NOG":
            case "SIB":
            case "PLT":
            case "PRM":
            case "FEO":
            case "BSH":
            case "BLO":
            case "RSO":
            case "GOL":
            case "GLH":
            case "ADE":
            case "ALH":
            case "ANZ":
            case "ARB":
            case "ARD":
            case "BHT":
            case "DAW":
            case "ERE":
            case "FAD":
            case "GRM":
            case "HDR":
            case "HED":
            case "LEB":
            case "MAK":
            case "MDA":
            case "MFL":
            case "MHR":
            case "NAJ":
            case "NJR":
            case "OMA":
            case "RAS":
            case "SHM":
            case "SHR":
            case "SRV":
            case "YAS":
            case "YEM":
            case "HSN":
            case "BTL":
            case "AKK":
            case "AYD":
            case "CND":
            case "DUL":
            case "IRQ":
            case "KAR":
            case "SYR":
            case "TRE":
            case "SRU":
            case "MEN":
            case "RAM":
            case "AVR":
            case "MLK":
            case "SME":
            case "ARL":
            case "MSY":
            case "RUM":
            case "ALG":
            case "FEZ":
            case "MAM":
            case "MOR":
            case "TRP":
            case "TUN":
            case "EGY":
            case "KBA":
            case "TFL":
            case "SOS":
            case "TLC":
            case "TGT":
            case "GHD":
            case "FZA":
            case "MZB":
            case "SLE":
            case "TET":
            case "MRK":
            case "KZH":
            case "KHI":
            case "SHY":
            case "KOK":
            case "BUK":
            case "AFG":
            case "KHO":
            case "PER":
            case "QAR":
            case "TIM":
            case "TRS":
            case "KRY":
            case "CIR":
            case "GAZ":
            case "IME":
            case "TAB":
            case "ORM":
            case "LRI":
            case "SIS":
            case "BPI":
            case "FRS":
            case "KRM":
            case "YZD":
            case "ISF":
            case "TBR":
            case "BSR":
            case "MGR":
            case "QOM":
            case "AZT":
            case "CHE":
            case "CHM":
            case "CRE":
            case "HUR":
            case "INC":
            case "IRO":
            case "MAY":
            case "SHA":
            case "ZAP":
            case "ASH":
            case "BEN":
            case "ETH":
            case "KON":
            case "MAL":
            case "NUB":
            case "SON":
            case "ZAN":
            case "ZIM":
            case "ADA":
            case "HAU":
            case "KBO":
            case "LOA":
            case "OYO":
            case "SOF":
            case "SOK":
            case "JOL":
            case "SFA":
            case "MBA":
            case "MLI":
            case "AJU":
            case "MDI":
            case "ENA":
            case "AFA":
            case "ALO":
            case "DAR":
            case "GLE":
            case "HAR":
            case "HOB":
            case "KAF":
            case "MED":
            case "MJE":
            case "MRE":
            case "PTE":
            case "WAR":
            case "BTI":
            case "BEJ":
            case "JIM":
            case "WLY":
            case "DAM":
            case "HDY":
            case "SOA":
            case "JJI":
            case "ABB":
            case "TYO":
            case "SYO":
            case "KSJ":
            case "LUB":
            case "LND":
            case "CKW":
            case "KIK":
            case "KZB":
            case "YAK":
            case "KLD":
            case "KUB":
            case "RWA":
            case "BUU":
            case "BUG":
            case "NKO":
            case "KRW":
            case "BNY":
            case "BSG":
            case "UBH":
            case "MRA":
            case "LDU":
            case "TBK":
            case "MKU":
            case "RZW":
            case "MIR":
            case "SKA":
            case "BTS":
            case "MFY":
            case "ANT":
            case "ANN":
            case "ARK":
            case "ATJ":
            case "AYU":
            case "BLI":
            case "BAN":
            case "BEI":
            case "CHA":
            case "CHG":
            case "CHK":
            case "DAI":
            case "JAP":
            case "AMA":
            case "ASA":
            case "CSK":
            case "DTE":
            case "HJO":
            case "HSK":
            case "HTK":
            case "IKE":
            case "IMG":
            case "MAE":
            case "MRI":
            case "ODA":
            case "OTM":
            case "OUC":
            case "SBA":
            case "SMZ":
            case "TKD":
            case "TKG":
            case "UES":
            case "YMN":
            case "RFR":
            case "ASK":
            case "KTB":
            case "ANU":
            case "AKM":
            case "AKT":
            case "CBA":
            case "ISK":
            case "ITO":
            case "KKC":
            case "KNO":
            case "OGS":
            case "SHN":
            case "STK":
            case "TKI":
            case "UTN":
            case "TTI":
            case "KHA":
            case "KHM":
            case "KOR":
            case "LNA":
            case "LUA":
            case "LXA":
            case "MAJ":
            case "MCH":
            case "MKS":
            case "MLC":
            case "MNG":
            case "MTR":
            case "OIR":
            case "PAT":
            case "PEG":
            case "QNG":
            case "RYU":
            case "SST":
            case "SUK":
            case "SUL":
            case "TAU":
            case "TIB":
            case "TOK":
            case "VIE":
            case "CZH":
            case "CSH":
            case "CXI":
            case "YUA":
            case "FRM":
            case "ILK":
            case "KLM":
            case "MGE":
            case "SOO":
            case "NVK":
            case "SOL":
            case "EJZ":
            case "NHX":
            case "MYR":
            case "MHX":
            case "MJZ":
            case "KRC":
            case "KLK":
            case "HMI":
            case "ZUN":
            case "KAS":
            case "CHH":
            case "KSD":
            case "SYG":
            case "UTS":
            case "KAM":
            case "GUG":
            case "PHA":
            case "CDL":
            case "CYI":
            case "CMI":
            case "MIN":
            case "YUE":
            case "SHU":
            case "NNG":
            case "CHC":
            case "TNG":
            case "WUU":
            case "QIC":
            case "YAN":
            case "JIN":
            case "LNG":
            case "QIN":
            case "HUA":
            case "CGS":
            case "BAL":
            case "BNG":
            case "BIJ":
            case "BAH":
            case "DLH":
            case "GOC":
            case "DEC":
            case "MAR":
            case "MUG":
            case "MYS":
            case "VIJ":
            case "AHM":
            case "ASS":
            case "GUJ":
            case "JNP":
            case "MAD":
            case "MLW":
            case "MAW":
            case "MER":
            case "MUL":
            case "NAG":
            case "NPL":
            case "ORI":
            case "PUN":
            case "SND":
            case "BRR":
            case "JAN":
            case "KRK":
            case "GDW":
            case "GRJ":
            case "GWA":
            case "DHU":
            case "KSH":
            case "KLN":
            case "KHD":
            case "ODH":
            case "VND":
            case "MAB":
            case "MEW":
            case "BDA":
            case "BST":
            case "BHU":
            case "BND":
            case "CEY":
            case "JSL":
            case "KAC":
            case "KMT":
            case "KGR":
            case "KAT":
            case "KOC":
            case "MLB":
            case "HAD":
            case "NGA":
            case "RMP":
            case "LDK":
            case "BGL":
            case "JFN":
            case "PTA":
            case "GHR":
            case "CHD":
            case "NGP":
            case "JAJ":
            case "TRT":
            case "CMP":
            case "BGA":
            case "TPR":
            case "SDY":
            case "BHA":
            case "YOR":
            case "DGL":
            case "MBL":
            case "SKK":
            case "IDR":
            case "JLV":
            case "PTL":
            case "NVR":
            case "RJK":
            case "JGD":
            case "PRB":
            case "PAN":
            case "KLP":
            case "SBP":
            case "PTT":
            case "RTT":
            case "KLH":
            case "KJH":
            case "PRD":
            case "JPR":
            case "SRG":
            case "KND":
            case "TLG":
            case "KLT":
            case "DNG":
            case "DTI":
            case "GRK":
            case "JML":
            case "LWA":
            case "MKP":
            case "SRM":
            case "KTU":
            case "KMN":
            case "GNG":
            case "TNJ":
            case "SRH":
            case "RJP":
            case "BAR":
            case "HSA":
            case "SMO":
            case "NZH":
            case "KOJ":
            case "MSA":
            case "HIN":
            case "ABE":
            case "APA":
            case "ASI":
            case "BLA":
            case "CAD":
            case "CHI":
            case "CHO":
            case "CHY":
            case "COM":
            case "FOX":
            case "ILL":
            case "LEN":
            case "MAH":
            case "MIK":
            case "MMI":
            case "NAH":
            case "OJI":
            case "OSA":
            case "OTT":
            case "PAW":
            case "PEQ":
            case "PIM":
            case "POT":
            case "POW":
            case "PUE":
            case "SHO":
            case "SIO":
            case "SUS":
            case "WCR":
            case "AIR":
            case "BON":
            case "DAH":
            case "DGB":
            case "FUL":
            case "JNN":
            case "KAN":
            case "KBU":
            case "KNG":
            case "KTS":
            case "MSI":
            case "NUP":
            case "TMB":
            case "YAO":
            case "YAT":
            case "ZAF":
            case "ZZZ":
            case "NDO":
            case "AVA":
            case "HSE":
            case "JOH":
            case "KED":
            case "LIG":
            case "MPH":
            case "MYA":
            case "PRK":
            case "MMA":
            case "MKA":
            case "MPA":
            case "MNI":
            case "KAL":
            case "HSI":
            case "BPR":
            case "CHU":
            case "HOD":
            case "CHV":
            case "KMC":
            case "BRT":
            case "ARP":
            case "CLM":
            case "CNK":
            case "COC":
            case "HDA":
            case "ITZ":
            case "KIC":
            case "KIO":
            case "MIX":
            case "SAL":
            case "TAR":
            case "TLA":
            case "TLX":
            case "TOT":
            case "WIC":
            case "XIU":
            case "BLM":
            case "BTN":
            case "CRB":
            case "DMK":
            case "PGR":
            case "PLB":
            case "PSA":
            case "SAK":
            case "SUN":
            case "KUT":
            case "BNJ":
            case "LFA":
            case "LNO":
            case "LUW":
            case "MGD":
            case "TER":
            case "TID":
            case "MAS":
            case "PGS":
            case "TDO":
            case "MNA":
            case "CEB":
            case "BTU":
            case "CSU":
            case "CCQ":
            case "MPC":
            case "MCA":
            case "QTO":
            case "CJA":
            case "HJA":
            case "PTG":
            case "TPQ":
            case "TPA":
            case "TUA":
            case "GUA":
            case "CUA":
            case "WKA":
            case "CYA":
            case "CLA":
            case "CRA":
            case "PCJ":
            case "ARW":
            case "CAB":
            case "ICM":
            case "MAT":
            case "COI":
            case "TEO":
            case "XAL":
            case "GAM":
            case "HST":
            case "CCM":
            case "OTO":
            case "YOK":
            case "LAC":
            case "KAQ":
            case "CTM":
            case "KER":
            case "ZNI":
            case "MSC":
            case "LIP":
            case "CHT":
            case "MIS":
            case "TAI":
            case "CNP":
            case "TON":
            case "YAQ":
            case "YKT":
            case "NSS":
            case "PRY":
            case "TOR":
            case "LIB":
            case "JMN":
            case "ROM":
            case "SYN":
            case "C00":
            case "C01":
            case "C02":
            case "C03":
            case "C04":
            case "C05":
            case "C06":
            case "C07":
            case "C08":
            case "C09":
            case "C10":
            case "C11":
            case "C12":
            case "C13":
            case "C14":
            case "C15":
            case "C16":
            case "C17":
            case "C18":
            case "C19":
            case "C20":
            case "C21":
            case "C22":
            case "C23":
            case "C24":
            case "C25":
            case "C26":
            case "C27":
            case "C28":
            case "C29":
            case "C30":
            case "C31":
            case "C32":
            case "C33":
            case "C34":
            case "C35":
            case "C36":
            case "C37":
            case "C38":
            case "C39":
            case "C40":
            case "C41":
            case "C42":
            case "C43":
            case "C44":
            case "C45":
            case "C46":
            case "C47":
            case "C48":
            case "C49":
            case "C50":
            case "C51":
            case "C52":
            case "C53":
            case "C54":
            case "C55":
            case "C56":
            case "C57":
            case "C58":
            case "C59":
            case "C60":
            case "C61":
            case "C62":
            case "C63":
            case "C64":
            case "C65":
            case "C66":
            case "C67":
            case "C68":
            case "C69":
            case "C70":
            case "C71":
            case "C72":
            case "C73":
            case "C74":
            case "K00":
            case "K01":
            case "K02":
            case "K03":
            case "K04":
            case "K05":
            case "K06":
            case "K07":
            case "K08":
            case "K09":
            case "K10":
            case "K11":
            case "K12":
            case "K13":
            case "K14":
            case "K15":
            case "K16":
            case "K17":
            case "K18":
            case "K19":
            case "K20":
            case "K21":
            case "K22":
            case "K23":
            case "K24":
            case "K25":
            case "K26":
            case "K27":
            case "K28":
            case "K29":
            case "K30":
            case "K31":
            case "K32":
            case "K33":
            case "K34":
            case "K35":
            case "K36":
            case "K37":
            case "K38":
            case "K39":
            case "K40":
            case "K41":
            case "K42":
            case "K43":
            case "K44":
            case "K45":
            case "K46":
            case "K47":
            case "K48":
            case "K49":
            case "K50":
            case "K51":
            case "K52":
            case "K53":
            case "K54":
            case "K55":
            case "K56":
            case "K57":
            case "K58":
            case "K59":
            case "K60":
            case "K61":
            case "K62":
            case "K63":
            case "K64":
            case "K65":
            case "K66":
            case "K67":
            case "K68":
            case "K69":
            case "K70":
            case "K71":
            case "K72":
            case "K73":
            case "K74":
            case "K75":
            case "K76":
            case "K77":
            case "K78":
            case "K79":
            case "K80":
            case "K81":
            case "K82":
            case "K83":
            case "K84":
            case "K85":
            case "K86":
            case "K87":
            case "K88":
            case "K89":
            case "K90":
            case "K91":
            case "K92":
            case "K93":
            case "K94":
            case "K95":
            case "K96":
            case "K97":
            case "K98":
            case "K99":
            case "E00":
            case "E01":
            case "E02":
            case "E03":
            case "E04":
            case "E05":
            case "E06":
            case "E07":
            case "E08":
            case "E09":
            case "E10":
            case "E11":
            case "E12":
            case "E13":
            case "E14":
            case "E15":
            case "E16":
            case "E17":
            case "E18":
            case "E19":
            case "E20":
            case "E21":
            case "E22":
            case "E23":
            case "E24":
            case "E25":
            case "E26":
            case "E27":
            case "E28":
            case "E29":
            case "E30":
            case "E31":
            case "E32":
            case "E33":
            case "E34":
            case "E35":
            case "E36":
            case "E37":
            case "E38":
            case "E39":
            case "E40":
            case "E41":
            case "E42":
            case "E43":
            case "E44":
            case "E45":
            case "E46":
            case "E47":
            case "E48":
            case "E49":
            case "T00":
            case "T01":
            case "T02":
            case "T03":
            case "T04":
            case "T05":
            case "T06":
            case "T07":
            case "T08":
            case "T09":
            case "T10":
            case "T11":
            case "T12":
            case "T13":
            case "T14":
            case "T15":
            case "T16":
            case "T17":
            case "T18":
            case "T19":
            case "T20":
            case "T21":
            case "T22":
            case "T23":
            case "T24":
            case "T25":
            case "T26":
            case "T27":
            case "T28":
            case "T29":
            case "T30":
            case "T31":
            case "T32":
            case "T33":
            case "T34":
            case "T35":
            case "T36":
            case "T37":
            case "T38":
            case "T39":
            case "T40":
            case "T41":
            case "T42":
            case "T43":
            case "T44":
            case "T45":
            case "T46":
            case "T47":
            case "T48":
            case "T49":
            case "T50":
            case "T51":
            case "T52":
            case "T53":
            case "T54":
            case "T55":
            case "T56":
            case "T57":
            case "T58":
            case "T59":
            case "T60":
            case "T61":
            case "T62":
            case "T63":
            case "T64":
            case "T65":
            case "T66":
            case "T67":
            case "T68":
            case "T69":
            case "T70":
            case "T71":
            case "T72":
            case "T73":
            case "T74":
            case "D00":
            case "D01":
            case "D02":
            case "D03":
            case "D04":
            case "D05":
            case "D06":
            case "D07":
            case "D08":
            case "D09":
            case "D10":
            case "D11":
            case "D12":
            case "D13":
            case "D14":
            case "D15":
            case "D16":
            case "D17":
            case "D18":
            case "D19":
            case "D20":
            case "D21":
            case "D22":
            case "D23":
            case "D24":
            case "D25":
            case "D26":
            case "D27":
            case "D28":
            case "D29":
            case "D30":
            case "D31":
            case "D32":
            case "D33":
            case "D34":
            case "D35":
            case "D36":
            case "D37":
            case "D38":
            case "D39":
            case "D40":
            case "D41":
            case "D42":
            case "D43":
            case "D44":
            case "D45":
            case "D46":
            case "D47":
            case "D48":
            case "D49":
            case "D50":
            case "D51":
            case "D52":
            case "D53":
            case "D54":
            case "D55":
            case "D56":
            case "D57":
            case "D58":
            case "D59":
            case "D60":
            case "D61":
            case "D62":
            case "D63":
            case "D64":
            case "D65":
            case "D66":
            case "D67":
            case "D68":
            case "D69":
            case "D70":
            case "D71":
            case "D72":
            case "D73":
            case "D74":
            case "O00":
            case "O01":
            case "O02":
            case "O03":
            case "O04":
            case "O05":
            case "O06":
            case "O07":
            case "O08":
            case "O09":
                return DataType.OBJECT;

            case "siege_balance":
            case "type":
            case "id":
            case "assigned_region":
            case "base":
            case "staging_province":
            case "target":
                return DataType.INT;

            case "fabricate_claim":
            case "slander_merchants":
            case "stealmap":
                return DataType.FLOAT;

            case "battle":
                return DataType.BOOL;

            default:
                System.out.println("Unknown ai key: " + key);
                return DataType.UNKNOWN; //If UNKNOWN, DataType.getType(value), mostly because a key can have multiple types (ex: value)
        }
    }

    public static DataType getTypeGamestate(String key) {
        switch (key) {
            default:
                System.out.println("Unknown gamestate key: " + key);
                return DataType.UNKNOWN; //If UNKNOWN, DataType.getType(value), mostly because a key can have multiple types (ex: value)
        }
    }
}
