package fr.graynaud.eu4saveeditor.common;

import fr.graynaud.eu4saveeditor.service.object.data.DataType;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public final class Keys {

    private static final Logger LOGGER = LoggerFactory.getLogger(Keys.class);

    //Keys I know have multiple possible types DO NOT ADD IN SWITCH
    private static final Set<String> BANNED_WORDS = Stream.of("type", "id", "value", "REB", "PIR", "NAT", "SWE", "DAN",
                                                              "FIN", "GOT", "NOR", "SHL", "SCA", "EST", "LVA", "SMI",
                                                              "KRL", "ICE", "ACH", "ALB", "ATH", "BOS", "BUL", "BYZ",
                                                              "CEP", "CRO", "CRT", "CYP", "EPI", "GRE", "KNI", "MOE",
                                                              "MOL", "MON", "NAX", "RAG", "RMN", "SER", "TRA", "WAL",
                                                              "HUN", "SLO", "TUR", "CNN", "CRN", "ENG", "LEI", "IRE",
                                                              "MNS", "SCO", "TYR", "WLS", "NOL", "GBR", "MTH", "ULS",
                                                              "DMS", "SLN", "KID", "HSC", "ORD", "TRY", "FLY", "MCM",
                                                              "KOI", "LOI", "BRZ", "CAN", "CHL", "COL", "HAT", "LAP",
                                                              "LOU", "MEX", "PEU", "PRG", "QUE", "CAM", "USA", "VNZ",
                                                              "AUS", "DNZ", "KRA", "LIT", "LIV", "MAZ", "POL", "PRU",
                                                              "KUR", "RIG", "TEU", "PLC", "VOL", "KIE", "CHR", "OKA",
                                                              "ALE", "ALS", "AMG", "AUV", "AVI", "BOU", "BRI", "BUR",
                                                              "CHP", "COR", "DAU", "FOI", "FRA", "GUY", "NEV", "NRM",
                                                              "ORL", "PIC", "PRO", "SPI", "TOU", "BER", "AAC", "ANH",
                                                              "ANS", "AUG", "BAD", "BAV", "BOH", "BRA", "BRE", "BRU",
                                                              "EFR", "FRN", "GER", "HAB", "HAM", "HAN", "HES", "HLR",
                                                              "KLE", "KOL", "LAU", "LOR", "LUN", "MAG", "MAI", "MEI",
                                                              "MKL", "MUN", "MVA", "OLD", "PAL", "POM", "SAX", "SIL",
                                                              "SLZ", "STY", "SWI", "THU", "TIR", "TRI", "ULM", "WBG",
                                                              "WES", "WUR", "NUM", "MEM", "VER", "NSA", "RVA", "DTT",
                                                              "ARA", "CAS", "CAT", "GRA", "NAV", "POR", "SPA", "GAL",
                                                              "LON", "ADU", "AQU", "ETR", "FER", "GEN", "ITA", "MAN",
                                                              "MLO", "MOD", "NAP", "PAP", "PAR", "PIS", "SAR", "SAV",
                                                              "SIC", "SIE", "TUS", "URB", "VEN", "MFA", "LUC", "LAN",
                                                              "JAI", "BRB", "FLA", "FRI", "GEL", "HAI", "HOL", "LIE",
                                                              "LUX", "NED", "UTR", "ARM", "AST", "CRI", "GEO", "KAZ",
                                                              "MOS", "NOV", "PSK", "QAS", "RUS", "RYA", "TVE", "UKR",
                                                              "YAR", "ZAZ", "NOG", "SIB", "PLT", "PRM", "FEO", "BSH",
                                                              "BLO", "RSO", "GOL", "GLH", "ADE", "ALH", "ANZ", "ARB",
                                                              "ARD", "BHT", "DAW", "ERE", "FAD", "GRM", "HDR", "HED",
                                                              "LEB", "MAK", "MDA", "MFL", "MHR", "NAJ", "NJR", "OMA",
                                                              "RAS", "SHM", "SHR", "SRV", "YAS", "YEM", "HSN", "BTL",
                                                              "AKK", "AYD", "CND", "DUL", "IRQ", "KAR", "SYR", "TRE",
                                                              "SRU", "MEN", "RAM", "AVR", "MLK", "SME", "ARL", "MSY",
                                                              "RUM", "ALG", "FEZ", "MAM", "MOR", "TRP", "TUN", "EGY",
                                                              "KBA", "TFL", "SOS", "TLC", "TGT", "GHD", "FZA", "MZB",
                                                              "KZH", "KHI", "SHY", "KOK", "BUK", "AFG", "KHO", "PER",
                                                              "QAR", "TIM", "TRS", "KRY", "CIR", "GAZ", "IME", "TAB",
                                                              "ORM", "LRI", "SIS", "BPI", "FRS", "KRM", "YZD", "ISF",
                                                              "TBR", "BSR", "MGR", "QOM", "AZT", "CHE", "CHM", "CRE",
                                                              "HUR", "INC", "IRO", "MAY", "SHA", "ZAP", "ASH", "BEN",
                                                              "ETH", "KON", "MAL", "NUB", "SON", "ZAN", "ZIM", "ADA",
                                                              "HAU", "KBO", "LOA", "OYO", "SOF", "SOK", "JOL", "SFA",
                                                              "MBA", "MLI", "AJU", "MDI", "ENA", "AFA", "ALO", "DAR",
                                                              "GLE", "HAR", "HOB", "KAF", "MED", "MJE", "MRE", "PTE",
                                                              "WAR", "BTI", "BEJ", "JIM", "WLY", "DAM", "HDY", "SOA",
                                                              "JJI", "ABB", "TYO", "SYO", "KSJ", "LUB", "LND", "CKW",
                                                              "KIK", "KZB", "YAK", "KLD", "KUB", "RWA", "BUU", "BUG",
                                                              "NKO", "KRW", "BNY", "BSG", "UBH", "MRA", "LDU", "TBK",
                                                              "MKU", "RZW", "MIR", "SKA", "BTS", "MFY", "ANT", "ANN",
                                                              "ARK", "ATJ", "AYU", "BLI", "BAN", "BEI", "CHA", "CHG",
                                                              "CHK", "DAI", "JAP", "AMA", "ASA", "CSK", "DTE", "HJO",
                                                              "HSK", "HTK", "IKE", "IMG", "MAE", "MRI", "ODA", "OTM",
                                                              "OUC", "SBA", "SMZ", "TKD", "TKG", "UES", "YMN", "RFR",
                                                              "ASK", "KTB", "ANU", "AKM", "AKT", "CBA", "ISK", "ITO",
                                                              "KKC", "KNO", "OGS", "SHN", "STK", "TKI", "UTN", "TTI",
                                                              "KHA", "KHM", "KOR", "LNA", "LUA", "LXA", "MAJ", "MCH",
                                                              "MKS", "MLC", "MNG", "MTR", "OIR", "PAT", "PEG", "QNG",
                                                              "RYU", "SST", "SUK", "SUL", "TAU", "TIB", "TOK", "VIE",
                                                              "CZH", "CSH", "CXI", "YUA", "MYR", "MHX", "MJZ", "KRC",
                                                              "KLK", "HMI", "ZUN", "KAS", "CHH", "KSD", "SYG", "UTS",
                                                              "KAM", "GUG", "CDL", "CYI", "CMI", "MIN", "YUE", "SHU",
                                                              "NNG", "CHC", "TNG", "WUU", "QIC", "YAN", "JIN", "LNG",
                                                              "QIN", "HUA", "CGS", "BAL", "BNG", "BIJ", "BAH", "DLH",
                                                              "GOC", "DEC", "MAR", "MUG", "MYS", "VIJ", "AHM", "ASS",
                                                              "GUJ", "JNP", "MAD", "MLW", "MAW", "MER", "MUL", "NAG",
                                                              "NPL", "ORI", "PUN", "SND", "BRR", "JAN", "KRK", "GDW",
                                                              "GRJ", "GWA", "DHU", "KSH", "KLN", "KHD", "ODH", "VND",
                                                              "MAB", "MEW", "BDA", "BST", "BHU", "BND", "CEY", "JSL",
                                                              "KAC", "KMT", "KGR", "KAT", "KOC", "MLB", "HAD", "NGA",
                                                              "RMP", "LDK", "BGL", "JFN", "PTA", "GHR", "CHD", "NGP",
                                                              "JAJ", "TRT", "CMP", "BGA", "TPR", "SDY", "BHA", "YOR",
                                                              "DGL", "BAR", "HSA", "SMO", "NZH", "KOJ", "MSA", "HIN",
                                                              "ABE", "APA", "ASI", "BLA", "CAD", "CHI", "CHO", "CHY",
                                                              "COM", "FOX", "ILL", "LEN", "MAH", "MIK", "MMI", "NAH",
                                                              "OJI", "OSA", "OTT", "PAW", "PEQ", "PIM", "POT", "POW",
                                                              "PUE", "SHO", "SIO", "SUS", "WCR", "AIR", "BON", "DAH",
                                                              "DGB", "FUL", "JNN", "KAN", "KBU", "KNG", "KTS", "MSI",
                                                              "NUP", "TMB", "YAO", "YAT", "ZAF", "ZZZ", "NDO", "AVA",
                                                              "HSE", "JOH", "KED", "LIG", "MPH", "MYA", "PRK", "CHU",
                                                              "HOD", "CHV", "KMC", "BRT", "ARP", "CLM", "CNK", "COC",
                                                              "HDA", "ITZ", "KIC", "KIO", "MIX", "SAL", "TAR", "TLA",
                                                              "TLX", "TOT", "WIC", "XIU", "BLM", "BTN", "CRB", "DMK",
                                                              "PGR", "PLB", "PSA", "SAK", "SUN", "KUT", "BNJ", "LFA",
                                                              "LNO", "LUW", "MGD", "TER", "TID", "MAS", "PGS", "TDO",
                                                              "MNA", "CEB", "BTU", "CSU", "CCQ", "MPC", "MCA", "QTO",
                                                              "CJA", "HJA", "PTG", "TPQ", "TPA", "TUA", "GUA", "CUA",
                                                              "WKA", "CYA", "CLA", "CRA", "PCJ", "ARW", "CAB", "ICM",
                                                              "JMN", "ROM", "JOM", "HAH", "ISR", "TEM", "TRL", "YKT",
                                                              "YAQ", "TAI", "MIS", "MSC", "ZNI", "XAL", "HSI", "MKA",
                                                              "MMA", "DNG", "EJZ", "NVK", "C00", "C01", "C02", "C03",
                                                              "modifier", "light_ship", "dynasty", "continent",
                                                              "original", "provinces", "C04", "C05", "C06", "C07",
                                                              "C08", "C09", "C10", "C11", "C12", "C13", "C14", "C15",
                                                              "O00", "O01", "O02", "O03", "O04", "O05", "O06", "O07",
                                                              "O08", "O09", "government", "defender", "leader",
                                                              "active", "trade", "institutions", "estate", "capital",
                                                              "fort_15th", "discovered_by", "unit", "action",
                                                              "workshop", "attacker", "barracks", "envoy", "fort_16th",
                                                              "marketplace", "regimental_camp", "shipyard",
                                                              "spy_network", "temple", "textile", "tradecompany",
                                                              "weapons", "wharf", "controller").collect(Collectors.toSet());

    private Keys() {
    }

    public static DataType getTypeMeta(String key) {
        switch (key) {
            case "date":
                return DataType.DATE;

            case "save_game":
            case "player":
            case "displayed_country_name":
            case "campaign_id":
            case "checksum":
            case "name":
            case "key":
            case "selector":
            case "localization":
                return DataType.STRING;

            case "savegame_version":
                return DataType.OBJECT;

            case "first":
            case "second":
            case "third":
            case "forth":
            case "campaign_length":
            case "id":
            case "comparison":
            case "sample_count":
                return DataType.INT;

            case "slander_merchants":
                return DataType.FLOAT;

            case "savegame_versions":
            case "dlc_enabled":
            case "mod_enabled":
                return DataType.LIST_STRING;

            case "multi_player":
            case "not_observer":
                return DataType.BOOL;

            case "campaign_stats":
                return DataType.LIST_OBJECT;

            default:
                if (LOGGER.isDebugEnabled() && !BANNED_WORDS.contains(key)) {
                    LOGGER.debug("Unknown meta key: " + key);
                }

                return DataType.UNKNOWN; //If UNKNOWN, DataType.getType(value), mostly because a key can have multiple types (ex: value)
        }
    }

    public static DataType getTypeAi(String key) {
        switch (key) {
            case "start_date":
            case "end_date":
                return DataType.DATE;

            case "checksum":
                return DataType.STRING;

            case "king_data":
            case "ai_data":
            case "diplomatic_biases":
            case "target_unit_id":
            case "focal_point":
            case "country":
            case "ai":
            case "unit":
            case "REB":
            case "PIR":
            case "NAT":
            case "SWE":
            case "DAN":
            case "FIN":
            case "GOT":
            case "NOR":
            case "SHL":
            case "SCA":
            case "EST":
            case "LVA":
            case "SMI":
            case "KRL":
            case "ICE":
            case "ACH":
            case "ALB":
            case "ATH":
            case "BOS":
            case "BUL":
            case "BYZ":
            case "CEP":
            case "CRO":
            case "CRT":
            case "CYP":
            case "EPI":
            case "GRE":
            case "KNI":
            case "MOE":
            case "MOL":
            case "MON":
            case "NAX":
            case "RAG":
            case "RMN":
            case "SER":
            case "TRA":
            case "WAL":
            case "HUN":
            case "SLO":
            case "TUR":
            case "CNN":
            case "CRN":
            case "ENG":
            case "LEI":
            case "IRE":
            case "MNS":
            case "SCO":
            case "TYR":
            case "WLS":
            case "NOL":
            case "GBR":
            case "MTH":
            case "ULS":
            case "DMS":
            case "SLN":
            case "KID":
            case "HSC":
            case "ORD":
            case "TRY":
            case "FLY":
            case "MCM":
            case "KOI":
            case "LOI":
            case "BRZ":
            case "CAN":
            case "CHL":
            case "COL":
            case "HAT":
            case "LAP":
            case "LOU":
            case "MEX":
            case "PEU":
            case "PRG":
            case "QUE":
            case "CAM":
            case "USA":
            case "VNZ":
            case "AUS":
            case "CAL":
            case "TEX":
            case "DNZ":
            case "KRA":
            case "LIT":
            case "LIV":
            case "MAZ":
            case "POL":
            case "PRU":
            case "KUR":
            case "RIG":
            case "TEU":
            case "PLC":
            case "VOL":
            case "KIE":
            case "CHR":
            case "OKA":
            case "ALE":
            case "ALS":
            case "AMG":
            case "AUV":
            case "AVI":
            case "BOU":
            case "BRI":
            case "BUR":
            case "CHP":
            case "COR":
            case "DAU":
            case "FOI":
            case "FRA":
            case "GUY":
            case "NEV":
            case "NRM":
            case "ORL":
            case "PIC":
            case "PRO":
            case "SPI":
            case "TOU":
            case "BER":
            case "AAC":
            case "ANH":
            case "ANS":
            case "AUG":
            case "BAD":
            case "BAV":
            case "BOH":
            case "BRA":
            case "BRE":
            case "BRU":
            case "EFR":
            case "FRN":
            case "GER":
            case "HAB":
            case "HAM":
            case "HAN":
            case "HES":
            case "HLR":
            case "KLE":
            case "KOL":
            case "LAU":
            case "LOR":
            case "LUN":
            case "MAG":
            case "MAI":
            case "MEI":
            case "MKL":
            case "MUN":
            case "MVA":
            case "OLD":
            case "PAL":
            case "POM":
            case "SAX":
            case "SIL":
            case "SLZ":
            case "STY":
            case "SWI":
            case "THU":
            case "TIR":
            case "TRI":
            case "ULM":
            case "WBG":
            case "WES":
            case "WUR":
            case "NUM":
            case "MEM":
            case "VER":
            case "NSA":
            case "RVA":
            case "DTT":
            case "ARA":
            case "CAS":
            case "CAT":
            case "GRA":
            case "NAV":
            case "POR":
            case "SPA":
            case "GAL":
            case "LON":
            case "ADU":
            case "VAL":
            case "ASU":
            case "MJO":
            case "AQU":
            case "ETR":
            case "FER":
            case "GEN":
            case "ITA":
            case "MAN":
            case "MLO":
            case "MOD":
            case "NAP":
            case "PAP":
            case "PAR":
            case "PIS":
            case "SAR":
            case "SAV":
            case "SIC":
            case "SIE":
            case "TUS":
            case "URB":
            case "VEN":
            case "MFA":
            case "LUC":
            case "LAN":
            case "JAI":
            case "BRB":
            case "FLA":
            case "FRI":
            case "GEL":
            case "HAI":
            case "HOL":
            case "LIE":
            case "LUX":
            case "NED":
            case "UTR":
            case "ARM":
            case "AST":
            case "CRI":
            case "GEO":
            case "KAZ":
            case "MOS":
            case "NOV":
            case "PSK":
            case "QAS":
            case "RUS":
            case "RYA":
            case "TVE":
            case "UKR":
            case "YAR":
            case "ZAZ":
            case "NOG":
            case "SIB":
            case "PLT":
            case "PRM":
            case "FEO":
            case "BSH":
            case "BLO":
            case "RSO":
            case "GOL":
            case "GLH":
            case "ADE":
            case "ALH":
            case "ANZ":
            case "ARB":
            case "ARD":
            case "BHT":
            case "DAW":
            case "ERE":
            case "FAD":
            case "GRM":
            case "HDR":
            case "HED":
            case "LEB":
            case "MAK":
            case "MDA":
            case "MFL":
            case "MHR":
            case "NAJ":
            case "NJR":
            case "OMA":
            case "RAS":
            case "SHM":
            case "SHR":
            case "SRV":
            case "YAS":
            case "YEM":
            case "HSN":
            case "BTL":
            case "AKK":
            case "AYD":
            case "CND":
            case "DUL":
            case "IRQ":
            case "KAR":
            case "SYR":
            case "TRE":
            case "SRU":
            case "MEN":
            case "RAM":
            case "AVR":
            case "MLK":
            case "SME":
            case "ARL":
            case "MSY":
            case "RUM":
            case "ALG":
            case "FEZ":
            case "MAM":
            case "MOR":
            case "TRP":
            case "TUN":
            case "EGY":
            case "KBA":
            case "TFL":
            case "SOS":
            case "TLC":
            case "TGT":
            case "GHD":
            case "FZA":
            case "MZB":
            case "SLE":
            case "TET":
            case "MRK":
            case "KZH":
            case "KHI":
            case "SHY":
            case "KOK":
            case "BUK":
            case "AFG":
            case "KHO":
            case "PER":
            case "QAR":
            case "TIM":
            case "TRS":
            case "KRY":
            case "CIR":
            case "GAZ":
            case "IME":
            case "TAB":
            case "ORM":
            case "LRI":
            case "SIS":
            case "BPI":
            case "FRS":
            case "KRM":
            case "YZD":
            case "ISF":
            case "TBR":
            case "BSR":
            case "MGR":
            case "QOM":
            case "AZT":
            case "CHE":
            case "CHM":
            case "CRE":
            case "HUR":
            case "INC":
            case "IRO":
            case "MAY":
            case "SHA":
            case "ZAP":
            case "ASH":
            case "BEN":
            case "ETH":
            case "KON":
            case "MAL":
            case "NUB":
            case "SON":
            case "ZAN":
            case "ZIM":
            case "ADA":
            case "HAU":
            case "KBO":
            case "LOA":
            case "OYO":
            case "SOF":
            case "SOK":
            case "JOL":
            case "SFA":
            case "MBA":
            case "MLI":
            case "AJU":
            case "MDI":
            case "ENA":
            case "AFA":
            case "ALO":
            case "DAR":
            case "GLE":
            case "HAR":
            case "HOB":
            case "KAF":
            case "MED":
            case "MJE":
            case "MRE":
            case "PTE":
            case "WAR":
            case "BTI":
            case "BEJ":
            case "JIM":
            case "WLY":
            case "DAM":
            case "HDY":
            case "SOA":
            case "JJI":
            case "ABB":
            case "TYO":
            case "SYO":
            case "KSJ":
            case "LUB":
            case "LND":
            case "CKW":
            case "KIK":
            case "KZB":
            case "YAK":
            case "KLD":
            case "KUB":
            case "RWA":
            case "BUU":
            case "BUG":
            case "NKO":
            case "KRW":
            case "BNY":
            case "BSG":
            case "UBH":
            case "MRA":
            case "LDU":
            case "TBK":
            case "MKU":
            case "RZW":
            case "MIR":
            case "SKA":
            case "BTS":
            case "MFY":
            case "ANT":
            case "ANN":
            case "ARK":
            case "ATJ":
            case "AYU":
            case "BLI":
            case "BAN":
            case "BEI":
            case "CHA":
            case "CHG":
            case "CHK":
            case "DAI":
            case "JAP":
            case "AMA":
            case "ASA":
            case "CSK":
            case "DTE":
            case "HJO":
            case "HSK":
            case "HTK":
            case "IKE":
            case "IMG":
            case "MAE":
            case "MRI":
            case "ODA":
            case "OTM":
            case "OUC":
            case "SBA":
            case "SMZ":
            case "TKD":
            case "TKG":
            case "UES":
            case "YMN":
            case "RFR":
            case "ASK":
            case "KTB":
            case "ANU":
            case "AKM":
            case "AKT":
            case "CBA":
            case "ISK":
            case "ITO":
            case "KKC":
            case "KNO":
            case "OGS":
            case "SHN":
            case "STK":
            case "TKI":
            case "UTN":
            case "TTI":
            case "KHA":
            case "KHM":
            case "KOR":
            case "LNA":
            case "LUA":
            case "LXA":
            case "MAJ":
            case "MCH":
            case "MKS":
            case "MLC":
            case "MNG":
            case "MTR":
            case "OIR":
            case "PAT":
            case "PEG":
            case "QNG":
            case "RYU":
            case "SST":
            case "SUK":
            case "SUL":
            case "TAU":
            case "TIB":
            case "TOK":
            case "VIE":
            case "CZH":
            case "CSH":
            case "CXI":
            case "YUA":
            case "FRM":
            case "ILK":
            case "KLM":
            case "MGE":
            case "SOO":
            case "NVK":
            case "SOL":
            case "EJZ":
            case "NHX":
            case "MYR":
            case "MHX":
            case "MJZ":
            case "KRC":
            case "KLK":
            case "HMI":
            case "ZUN":
            case "KAS":
            case "CHH":
            case "KSD":
            case "SYG":
            case "UTS":
            case "KAM":
            case "GUG":
            case "PHA":
            case "CDL":
            case "CYI":
            case "CMI":
            case "MIN":
            case "YUE":
            case "SHU":
            case "NNG":
            case "CHC":
            case "TNG":
            case "WUU":
            case "QIC":
            case "YAN":
            case "JIN":
            case "LNG":
            case "QIN":
            case "HUA":
            case "CGS":
            case "BAL":
            case "BNG":
            case "BIJ":
            case "BAH":
            case "DLH":
            case "GOC":
            case "DEC":
            case "MAR":
            case "MUG":
            case "MYS":
            case "VIJ":
            case "AHM":
            case "ASS":
            case "GUJ":
            case "JNP":
            case "MAD":
            case "MLW":
            case "MAW":
            case "MER":
            case "MUL":
            case "NAG":
            case "NPL":
            case "ORI":
            case "PUN":
            case "SND":
            case "BRR":
            case "JAN":
            case "KRK":
            case "GDW":
            case "GRJ":
            case "GWA":
            case "DHU":
            case "KSH":
            case "KLN":
            case "KHD":
            case "ODH":
            case "VND":
            case "MAB":
            case "MEW":
            case "BDA":
            case "BST":
            case "BHU":
            case "BND":
            case "CEY":
            case "JSL":
            case "KAC":
            case "KMT":
            case "KGR":
            case "KAT":
            case "KOC":
            case "MLB":
            case "HAD":
            case "NGA":
            case "RMP":
            case "LDK":
            case "BGL":
            case "JFN":
            case "PTA":
            case "GHR":
            case "CHD":
            case "NGP":
            case "JAJ":
            case "TRT":
            case "CMP":
            case "BGA":
            case "TPR":
            case "SDY":
            case "BHA":
            case "YOR":
            case "DGL":
            case "MBL":
            case "SKK":
            case "IDR":
            case "JLV":
            case "PTL":
            case "NVR":
            case "RJK":
            case "JGD":
            case "PRB":
            case "PAN":
            case "KLP":
            case "SBP":
            case "PTT":
            case "RTT":
            case "KLH":
            case "KJH":
            case "PRD":
            case "JPR":
            case "SRG":
            case "KND":
            case "TLG":
            case "KLT":
            case "DNG":
            case "DTI":
            case "GRK":
            case "JML":
            case "LWA":
            case "MKP":
            case "SRM":
            case "KTU":
            case "KMN":
            case "GNG":
            case "TNJ":
            case "SRH":
            case "RJP":
            case "BAR":
            case "HSA":
            case "SMO":
            case "NZH":
            case "KOJ":
            case "MSA":
            case "HIN":
            case "ABE":
            case "APA":
            case "ASI":
            case "BLA":
            case "CAD":
            case "CHI":
            case "CHO":
            case "CHY":
            case "COM":
            case "FOX":
            case "ILL":
            case "LEN":
            case "MAH":
            case "MIK":
            case "MMI":
            case "NAH":
            case "OJI":
            case "OSA":
            case "OTT":
            case "PAW":
            case "PEQ":
            case "PIM":
            case "POT":
            case "POW":
            case "PUE":
            case "SHO":
            case "SIO":
            case "SUS":
            case "WCR":
            case "AIR":
            case "BON":
            case "DAH":
            case "DGB":
            case "FUL":
            case "JNN":
            case "KAN":
            case "KBU":
            case "KNG":
            case "KTS":
            case "MSI":
            case "NUP":
            case "TMB":
            case "YAO":
            case "YAT":
            case "ZAF":
            case "ZZZ":
            case "NDO":
            case "AVA":
            case "HSE":
            case "JOH":
            case "KED":
            case "LIG":
            case "MPH":
            case "MYA":
            case "PRK":
            case "MMA":
            case "MKA":
            case "MPA":
            case "MNI":
            case "KAL":
            case "HSI":
            case "BPR":
            case "CHU":
            case "HOD":
            case "CHV":
            case "KMC":
            case "BRT":
            case "ARP":
            case "CLM":
            case "CNK":
            case "COC":
            case "HDA":
            case "ITZ":
            case "KIC":
            case "KIO":
            case "MIX":
            case "SAL":
            case "TAR":
            case "TLA":
            case "TLX":
            case "TOT":
            case "WIC":
            case "XIU":
            case "BLM":
            case "BTN":
            case "CRB":
            case "DMK":
            case "PGR":
            case "PLB":
            case "PSA":
            case "SAK":
            case "SUN":
            case "KUT":
            case "BNJ":
            case "LFA":
            case "LNO":
            case "LUW":
            case "MGD":
            case "TER":
            case "TID":
            case "MAS":
            case "PGS":
            case "TDO":
            case "MNA":
            case "CEB":
            case "BTU":
            case "CSU":
            case "CCQ":
            case "MPC":
            case "MCA":
            case "QTO":
            case "CJA":
            case "HJA":
            case "PTG":
            case "TPQ":
            case "TPA":
            case "TUA":
            case "GUA":
            case "CUA":
            case "WKA":
            case "CYA":
            case "CLA":
            case "CRA":
            case "PCJ":
            case "ARW":
            case "CAB":
            case "ICM":
            case "MAT":
            case "COI":
            case "TEO":
            case "XAL":
            case "GAM":
            case "HST":
            case "CCM":
            case "OTO":
            case "YOK":
            case "LAC":
            case "KAQ":
            case "CTM":
            case "KER":
            case "ZNI":
            case "MSC":
            case "LIP":
            case "CHT":
            case "MIS":
            case "TAI":
            case "CNP":
            case "TON":
            case "YAQ":
            case "YKT":
            case "NSS":
            case "PRY":
            case "TOR":
            case "LIB":
            case "JMN":
            case "ROM":
            case "SYN":
            case "C00":
            case "C01":
            case "C02":
            case "C03":
            case "C04":
            case "C05":
            case "C06":
            case "C07":
            case "C08":
            case "C09":
            case "C10":
            case "C11":
            case "C12":
            case "C13":
            case "C14":
            case "C15":
            case "C16":
            case "C17":
            case "C18":
            case "C19":
            case "C20":
            case "C21":
            case "C22":
            case "C23":
            case "C24":
            case "C25":
            case "C26":
            case "C27":
            case "C28":
            case "C29":
            case "C30":
            case "C31":
            case "C32":
            case "C33":
            case "C34":
            case "C35":
            case "C36":
            case "C37":
            case "C38":
            case "C39":
            case "C40":
            case "C41":
            case "C42":
            case "C43":
            case "C44":
            case "C45":
            case "C46":
            case "C47":
            case "C48":
            case "C49":
            case "C50":
            case "C51":
            case "C52":
            case "C53":
            case "C54":
            case "C55":
            case "C56":
            case "C57":
            case "C58":
            case "C59":
            case "C60":
            case "C61":
            case "C62":
            case "C63":
            case "C64":
            case "C65":
            case "C66":
            case "C67":
            case "C68":
            case "C69":
            case "C70":
            case "C71":
            case "C72":
            case "C73":
            case "C74":
            case "K00":
            case "K01":
            case "K02":
            case "K03":
            case "K04":
            case "K05":
            case "K06":
            case "K07":
            case "K08":
            case "K09":
            case "K10":
            case "K11":
            case "K12":
            case "K13":
            case "K14":
            case "K15":
            case "K16":
            case "K17":
            case "K18":
            case "K19":
            case "K20":
            case "K21":
            case "K22":
            case "K23":
            case "K24":
            case "K25":
            case "K26":
            case "K27":
            case "K28":
            case "K29":
            case "K30":
            case "K31":
            case "K32":
            case "K33":
            case "K34":
            case "K35":
            case "K36":
            case "K37":
            case "K38":
            case "K39":
            case "K40":
            case "K41":
            case "K42":
            case "K43":
            case "K44":
            case "K45":
            case "K46":
            case "K47":
            case "K48":
            case "K49":
            case "K50":
            case "K51":
            case "K52":
            case "K53":
            case "K54":
            case "K55":
            case "K56":
            case "K57":
            case "K58":
            case "K59":
            case "K60":
            case "K61":
            case "K62":
            case "K63":
            case "K64":
            case "K65":
            case "K66":
            case "K67":
            case "K68":
            case "K69":
            case "K70":
            case "K71":
            case "K72":
            case "K73":
            case "K74":
            case "K75":
            case "K76":
            case "K77":
            case "K78":
            case "K79":
            case "K80":
            case "K81":
            case "K82":
            case "K83":
            case "K84":
            case "K85":
            case "K86":
            case "K87":
            case "K88":
            case "K89":
            case "K90":
            case "K91":
            case "K92":
            case "K93":
            case "K94":
            case "K95":
            case "K96":
            case "K97":
            case "K98":
            case "K99":
            case "E00":
            case "E01":
            case "E02":
            case "E03":
            case "E04":
            case "E05":
            case "E06":
            case "E07":
            case "E08":
            case "E09":
            case "E10":
            case "E11":
            case "E12":
            case "E13":
            case "E14":
            case "E15":
            case "E16":
            case "E17":
            case "E18":
            case "E19":
            case "E20":
            case "E21":
            case "E22":
            case "E23":
            case "E24":
            case "E25":
            case "E26":
            case "E27":
            case "E28":
            case "E29":
            case "E30":
            case "E31":
            case "E32":
            case "E33":
            case "E34":
            case "E35":
            case "E36":
            case "E37":
            case "E38":
            case "E39":
            case "E40":
            case "E41":
            case "E42":
            case "E43":
            case "E44":
            case "E45":
            case "E46":
            case "E47":
            case "E48":
            case "E49":
            case "T00":
            case "T01":
            case "T02":
            case "T03":
            case "T04":
            case "T05":
            case "T06":
            case "T07":
            case "T08":
            case "T09":
            case "T10":
            case "T11":
            case "T12":
            case "T13":
            case "T14":
            case "T15":
            case "T16":
            case "T17":
            case "T18":
            case "T19":
            case "T20":
            case "T21":
            case "T22":
            case "T23":
            case "T24":
            case "T25":
            case "T26":
            case "T27":
            case "T28":
            case "T29":
            case "T30":
            case "T31":
            case "T32":
            case "T33":
            case "T34":
            case "T35":
            case "T36":
            case "T37":
            case "T38":
            case "T39":
            case "T40":
            case "T41":
            case "T42":
            case "T43":
            case "T44":
            case "T45":
            case "T46":
            case "T47":
            case "T48":
            case "T49":
            case "T50":
            case "T51":
            case "T52":
            case "T53":
            case "T54":
            case "T55":
            case "T56":
            case "T57":
            case "T58":
            case "T59":
            case "T60":
            case "T61":
            case "T62":
            case "T63":
            case "T64":
            case "T65":
            case "T66":
            case "T67":
            case "T68":
            case "T69":
            case "T70":
            case "T71":
            case "T72":
            case "T73":
            case "T74":
            case "D00":
            case "D01":
            case "D02":
            case "D03":
            case "D04":
            case "D05":
            case "D06":
            case "D07":
            case "D08":
            case "D09":
            case "D10":
            case "D11":
            case "D12":
            case "D13":
            case "D14":
            case "D15":
            case "D16":
            case "D17":
            case "D18":
            case "D19":
            case "D20":
            case "D21":
            case "D22":
            case "D23":
            case "D24":
            case "D25":
            case "D26":
            case "D27":
            case "D28":
            case "D29":
            case "D30":
            case "D31":
            case "D32":
            case "D33":
            case "D34":
            case "D35":
            case "D36":
            case "D37":
            case "D38":
            case "D39":
            case "D40":
            case "D41":
            case "D42":
            case "D43":
            case "D44":
            case "D45":
            case "D46":
            case "D47":
            case "D48":
            case "D49":
            case "D50":
            case "D51":
            case "D52":
            case "D53":
            case "D54":
            case "D55":
            case "D56":
            case "D57":
            case "D58":
            case "D59":
            case "D60":
            case "D61":
            case "D62":
            case "D63":
            case "D64":
            case "D65":
            case "D66":
            case "D67":
            case "D68":
            case "D69":
            case "D70":
            case "D71":
            case "D72":
            case "D73":
            case "D74":
            case "O00":
            case "O01":
            case "O02":
            case "O03":
            case "O04":
            case "O05":
            case "O06":
            case "O07":
            case "O08":
            case "O09":
                return DataType.OBJECT;

            case "siege_balance":
            case "type":
            case "id":
            case "assigned_region":
            case "base":
            case "staging_province":
            case "target":
                return DataType.INT;

            case "fabricate_claim":
            case "slander_merchants":
            case "stealmap":
                return DataType.FLOAT;

            case "battle":
                return DataType.BOOL;

            default:
                if (LOGGER.isDebugEnabled() && !BANNED_WORDS.contains(key)) {
                    LOGGER.debug("Unknown ai key: " + key);
                }

                return DataType.UNKNOWN; //If UNKNOWN, DataType.getType(value), mostly because a key can have multiple types (ex: value)
        }
    }

    public static DataType getTypeGamestate(String key) {
        switch (key) {
            case "start_date":
            case "date":
            case "trading_policy_date":
            case "most_recent_treasure_ship_passage":
            case "schools_initiated":
            case "dlh_bahlul_lodi_flag":
            case "plc_union_outcome_flag":
            case "mol_hungarian_march":
            case "enable_stop_shadow_kingdom":
            case "wih_meerabai_flag":
            case "wih_barbaracilli_flag":
            case "wih_eleniethiopia_flag":
            case "death_of_shah_rukh":
            case "constantinople_restored":
            case "lollard_heresy":
            case "wih_caterina_sforza_flag":
            case "coptic_qasr_ibrim_liberated":
            case "new_world_discovered":
            case "italy_out_of_HRE":
            case "wih_anacaona_flag":
            case "wih_lucreziaborgia_flag":
            case "wih_suriyothai_flag":
            case "wih_heonanseolheon_flag":
            case "no_legatus_natus":
            case "no_primas_germaniae":
            case "counter_reformation":
            case "wih_anneboleyn_flag":
            case "wih_dorotheasaxelauenburg_flag":
            case "wih_inesdesuarez_flag":
            case "triangle_happened":
            case "wih_kenausimonsdochterhasselaer_flag":
            case "dorgon_flag":
            case "hagia_sophia_now_mosque":
            case "japan_has_encountered_the_west":
            case "death_of_haji_giray":
            case "wih_safiyesultan_flag":
            case "circumnavigation_completed":
            case "wih_lamalince_flag":
            case "inc_smallpox":
            case "wih_roxelana_tur_flag":
            case "eth_start_of_the_oromo":
            case "last_janissary_spawn":
            case "expiry_date":
            case "enable":
            case "crusade_start":
            case "last_excom":
            case "birth_date":
            case "defender_date":
            case "last_estate_grant":
            case "last_looted":
            case "province_had_influenza":
                return DataType.DATE;

            case "current_age":
            case "area":
            case "country":
            case "which":
            case "definitions":
            case "trading_policy":
            case "name":
            case "tag":
            case "key":
            case "heretic":
            case "religion":
            case "culture":
            case "independence":
            case "emperor":
            case "papal_state":
            case "first":
            case "second":
            case "crusade_target":
            case "previous_controller":
            case "owner":
            case "original_culture":
            case "original_religion":
            case "add_core":
            case "trade_goods":
            case "action_token":
            case "actor":
            case "likely_rebels":
            case "recipient":
            case "territorial_core":
            case "hostile_core_creation_tag":
            case "hostile_core_creation_desc":
                return DataType.STRING;

            case "gameplaysettings":
            case "saved_event_target":
            case "flags":
            case "map_area_data":
            case "brittany_area":
            case "state":
            case "country_state":
            case "active_edict":
            case "node":
            case "incoming":
            case "current_banner":
            case "investments":
            case "normandy_area":
            case "provence_area":
            case "poitou_area":
            case "guyenne_area":
            case "pyrenees_area":
            case "languedoc_area":
            case "bourgogne_area":
            case "massif_central_area":
            case "savoy_dauphine_area":
            case "lorraine_area":
            case "picardy_area":
            case "ile_de_france_area":
            case "champagne_area":
            case "loire_area":
            case "wallonia_area":
            case "holland_area":
            case "flanders_area":
            case "netherlands_area":
            case "frisia_area":
            case "aragon_area":
            case "catalonia_area":
            case "valencia_area":
            case "lower_andalucia_area":
            case "upper_andalucia_area":
            case "castille_area":
            case "toledo_area":
            case "asturias_area":
            case "galicia_area":
            case "baleares_area":
            case "basque_country":
            case "leon_area":
            case "beieras_area":
            case "alentejo_area":
            case "macaronesia_area":
            case "venetia_area":
            case "lombardy_area":
            case "piedmont_area":
            case "tuscany_area":
            case "liguria_area":
            case "corsica_sardinia_area":
            case "sicily_area":
            case "naples_area":
            case "calabria_area":
            case "apulia_area":
            case "emilia_romagna_area":
            case "central_italy_area":
            case "munster_area":
            case "connacht_area":
            case "leinster_area":
            case "ulster_area":
            case "kingdom_of_the_isles_area":
            case "highlands_area":
            case "lowlands_area":
            case "wales_area":
            case "scottish_marches_area":
            case "yorkshire_area":
            case "west_midlands_area":
            case "east_midlands_area":
            case "wessex_area":
            case "home_counties_area":
            case "east_anglia_area":
            case "jutland_area":
            case "denmark_area":
            case "skaneland_area":
            case "gotaland_area":
            case "vastra_gotaland_area":
            case "svealand_area":
            case "ostra_svealand_area":
            case "norrland_area":
            case "finland_area":
            case "bothnia_area":
            case "laponia_area":
            case "karelia_area":
            case "north_karelia":
            case "northern_norway":
            case "eastern_norway":
            case "western_norway":
            case "subarctic_islands_area":
            case "iceland_area":
            case "estonia_ingria_area":
            case "livonia_area":
            case "curonia_area":
            case "east_prussia_area":
            case "west_prussia_area":
            case "wielkopolska_area":
            case "malopolska_area":
            case "red_ruthenia_area":
            case "podolia_volhynia_area":
            case "volhynia_area":
            case "pripyat_area":
            case "mazovia_area":
            case "central_poland_area":
            case "sandomierz_area":
            case "kuyavia_area":
            case "samogitia_area":
            case "lithuania_area":
            case "west_dniepr_area":
            case "east_dniepr_area":
            case "chernigov_area":
            case "sloboda_ukraine_area":
            case "yedisan_area":
            case "zaporizhia_area":
            case "azov_area":
            case "crimea_area":
            case "white_ruthenia_area":
            case "minsk_area":
            case "ryazan_area":
            case "moscow_area":
            case "vladimir_area":
            case "yaroslavl_area":
            case "tver_area":
            case "suzdal_area":
            case "smolensk_area":
            case "oka_area":
            case "novgorod_area":
            case "pskov_area":
            case "vologda_area":
            case "beloozero_area":
            case "astrakhan_area":
            case "lower_don_area":
            case "kazan_area":
            case "samara_area":
            case "lower_yik_area":
            case "nogai_area":
            case "ural_area":
            case "pomor_area":
            case "arkhangelsk_area":
            case "bashkiria_area":
            case "volga_area":
            case "galich_area":
            case "kama_area":
            case "tambov_area":
            case "saratov_area":
            case "silesia_area":
            case "bohemia_area":
            case "erzgebirge_area":
            case "south_saxony_area":
            case "upper_bavaria_area":
            case "lower_bavaria_area":
            case "lower_swabia_area":
            case "franconia_area":
            case "upper_swabia_area":
            case "northern_saxony_area":
            case "thuringia_area":
            case "neumark_area":
            case "mittelmark_area":
            case "vorpommern_area":
            case "hinter_pommern_area":
            case "tirol_area":
            case "austria_proper_area":
            case "inner_austria_area":
            case "carinthia_area":
            case "switzerland_area":
            case "romandie_area":
            case "upper_rhineland_area":
            case "palatinate_area":
            case "north_rhine_area":
            case "lower_rhineland_area":
            case "westphalia_area":
            case "hesse_area":
            case "braunschweig_area":
            case "weser_area":
            case "holstein_area":
            case "lower_saxony_area":
            case "mecklenburg_area":
            case "macedonia_area":
            case "morea_area":
            case "northern_greece_area":
            case "thrace_area":
            case "bulgaria_area":
            case "wallachia_area":
            case "moldavia_area":
            case "transylvania_area":
            case "southern_transylvania_area":
            case "slovakia_area":
            case "serbia_area":
            case "rascia_area":
            case "albania_area":
            case "bosnia_area":
            case "croatia_area":
            case "east_adriatic_coast_area":
            case "alfold_area":
            case "transdanubia_area":
            case "imereti_area":
            case "samtskhe_area":
            case "kartli_kakheti_area":
            case "armenia_area":
            case "shirvan_area":
            case "circassia_area":
            case "dagestan_area":
            case "rum_area":
            case "erzurum_area":
            case "hudavendigar_area":
            case "germiyan_area":
            case "aydin_area":
            case "ankara_area":
            case "aegean_archipelago_area":
            case "kastamonu_area":
            case "karaman_area":
            case "cukurova_area":
            case "aleppo_area":
            case "syria_area":
            case "trans_jordan_area":
            case "palestine_area":
            case "dulkadir_area":
            case "iraq_arabi_area":
            case "basra_area":
            case "luristan_area":
            case "north_kurdistan_area":
            case "khuzestan_area":
            case "shahrizor_area":
            case "al_jazira_area":
            case "bahrain_area":
            case "pirate_coast_area":
            case "tabuk_area":
            case "medina_area":
            case "mecca_area":
            case "asir_area":
            case "tihama_al_yemen_area":
            case "upper_yemen_area":
            case "yemen_area":
            case "hadramut_area":
            case "mahra_area":
            case "dhofar_area":
            case "oman_area":
            case "mascat_area":
            case "gulf_of_arabia_area":
            case "al_wahat_area":
            case "delta_area":
            case "bahari_area":
            case "vostani_area":
            case "said_area":
            case "cyrenaica_area":
            case "tunisia_area":
            case "algiers_area":
            case "barbary_coast_area":
            case "kabylia_area":
            case "hautes_plaines_area":
            case "tafilalt_area":
            case "sus_area":
            case "southern_morocco_area":
            case "western_morocco_area":
            case "marrekesh_area":
            case "northern_morocco_area":
            case "madagascar_highlands_area":
            case "betsimasaraka_area":
            case "sakalava_area":
            case "southern_madagascar":
            case "lower_zambezi_area":
            case "upper_zambezi_area":
            case "shire_area":
            case "butua_area":
            case "zimbabwe_area":
            case "ruvuma_area":
            case "ngonde_area":
            case "uticulo_makuana_area":
            case "quelimane_area":
            case "limpopo_area":
            case "buha_area":
            case "buzinza_area":
            case "luba_area":
            case "katanga_area":
            case "zambia_area":
            case "chokwe_area":
            case "rwanda_area":
            case "uganda_area":
            case "bunyoro_area":
            case "kasai_area":
            case "sankuru_area":
            case "lower_kasai":
            case "ogaden_area":
            case "lower_nubia_area":
            case "dongola_area":
            case "upper_nubia_area":
            case "red_sea_coast_area":
            case "ifat_area":
            case "southern_ethiopia_area":
            case "hadiya_area":
            case "central_ethiopia_area":
            case "damot_area":
            case "shewa_area":
            case "mogadishu_area":
            case "ajuuran_area":
            case "majarteen_area":
            case "indian_ocean_islands_area":
            case "western_sahara_area":
            case "jolof_area":
            case "tekrur_area":
            case "baghena_area":
            case "manding_area":
            case "futa_jallon_area":
            case "massina_area":
            case "jenne_area":
            case "niger_bend_area":
            case "upper_volta_area":
            case "kong_area":
            case "lower_volta_area":
            case "lower_niger_area":
            case "hausa_area":
            case "katsina_area":
            case "zazzau_area":
            case "bornu_area":
            case "kanem_area":
            case "adamawa_plateau_area":
            case "dendi_area":
            case "azbin_area":
            case "east_azbin_area":
            case "atacora_oueme_area":
            case "benin_area":
            case "west_africa_coast_area":
            case "matamba_area":
            case "coastal_kongo":
            case "kongo_area":
            case "angola_namibia_area":
            case "makran_area":
            case "sistan_area":
            case "kalat_area":
            case "ferghana_area":
            case "arys_area":
            case "kyzylkum_area":
            case "transoxiana_area":
            case "termez_area":
            case "khiva_area":
            case "kabulistan_area":
            case "transcaspia_area":
            case "mashhad_area":
            case "herat_area":
            case "birjand_area":
            case "ghor_area":
            case "merv_area":
            case "balkh_area":
            case "kerman_area":
            case "persian_gulf_coast":
            case "mogostan_area":
            case "farsistan_area":
            case "iraq_e_ajam_area":
            case "azerbaijan_area":
            case "isfahan_area":
            case "tabriz_area":
            case "tabarestan_area":
            case "sirhind_area":
            case "sind_sagar_area":
            case "oudh_area":
            case "katehar_area":
            case "purvanchal_area":
            case "upper_doab_area":
            case "lower_doab_area":
            case "lahore_area":
            case "multan_area":
            case "naga_hills_area":
            case "east_bengal_area":
            case "north_bengal_area":
            case "tripura_area":
            case "bihar_area":
            case "mithila_area":
            case "jharkhand_area":
            case "upper_mahanadi_area":
            case "gaur_area":
            case "west_bengal_area":
            case "gird_area":
            case "baghelkhand_area":
            case "bundelkhand_area":
            case "gondwana_area":
            case "orissa_area":
            case "garjat_area":
            case "telingana_area":
            case "golconda_area":
            case "andhra_area":
            case "raichur_doab_area":
            case "khandesh_area":
            case "rayalaseema_area":
            case "malabar_area":
            case "malwa_area":
            case "mewar_area":
            case "jangladesh_area":
            case "marwar_area":
            case "jaipur_area":
            case "sindh_area":
            case "northern_sindh_area":
            case "north_carnatic_area":
            case "south_carnatic_area":
            case "madura_area":
            case "tanjore_area":
            case "kongu_area":
            case "konkan_area":
            case "desh_area":
            case "ahmednagar_area":
            case "kanara_area":
            case "maidan_area":
            case "mysore_area":
            case "berar_area":
            case "assam_area":
            case "himalayan_hills_area":
            case "nepal_area":
            case "baisi_rajya_area":
            case "bhutan_area":
            case "kashmir_area":
            case "lanka_area":
            case "south_lanka_area":
            case "ahmedabad_area":
            case "patan_area":
            case "tapti_area":
            case "saurashtra_area":
            case "upper_burma_area":
            case "central_burma_area":
            case "chindwin_area":
            case "kachin_area":
            case "shan_hill_area":
            case "karenni_area":
            case "malaya_area":
            case "malacca_area":
            case "khorat_area":
            case "champa_area":
            case "cambodia_area":
            case "lower_burma_area":
            case "arakan_area":
            case "mekong_area":
            case "tenasserim_area":
            case "north_tenasserim_area":
            case "vietnam_area":
            case "red_river_delta_area":
            case "south_laos_area":
            case "north_laos_area":
            case "central_thai_area":
            case "northern_thai_area":
            case "mindanao_area":
            case "west_mindanao_area":
            case "visayas_area":
            case "palawan_area":
            case "luzon_area":
            case "southern_luzon_area":
            case "north_sumatra_area":
            case "batak_area":
            case "central_sumatra_area":
            case "minangkabau_area":
            case "south_sumatra_area":
            case "east_java_area":
            case "central_java_area":
            case "west_java_area":
            case "kutai_area":
            case "brunei_area":
            case "spice_islands_area":
            case "lesser_sunda_islands_area":
            case "south_sulawesi_area":
            case "pyongan_area":
            case "hamgyeong_area":
            case "western_korea_area":
            case "eastern_korea_area":
            case "south_korea_area":
            case "hokkaido_area":
            case "hokuriku_area":
            case "kanto_area":
            case "eastern_kanto_area":
            case "kyushu_area":
            case "northern_kyushu":
            case "shikoku_area":
            case "eastern_chubu_area":
            case "chubu_area":
            case "kinai_area":
            case "thohoku_area":
            case "sanindo_area":
            case "saigoku_area":
            case "kamchatka_area":
            case "buryatia_area":
            case "ob_area":
            case "perm_area":
            case "balchasj_area":
            case "kazakhstan_area":
            case "syr_darya_area":
            case "yrtesh_area":
            case "ishim_area":
            case "aqmola_area":
            case "heilongjiang_area":
            case "east_heilongjiang_area":
            case "central_heilongjiang_area":
            case "cicigar_area":
            case "ilan_hala_area":
            case "sakhalin_area":
            case "central_jilin_area":
            case "ningguta_area":
            case "furdan_area":
            case "jilin_area":
            case "liaoning_area":
            case "ordos_area":
            case "eastern_mongolia":
            case "chahar_area":
            case "inner_mongolia_area":
            case "outer_mongolia_area":
            case "xilin_gol_area":
            case "altai_sayan_area":
            case "tannu_uriankhai_area":
            case "central_mongolia_area":
            case "uliastai_area":
            case "jetysuu_area":
            case "kashgaria_area":
            case "shanshan_area":
            case "turpan_kumul_area":
            case "zungaria_area":
            case "amdo_area":
            case "tsang_area":
            case "north_zungaria":
            case "kham_area":
            case "utsang_area":
            case "ngari_area":
            case "hebei_area":
            case "south_hebei_area":
            case "shandong_area":
            case "jiangsu_area":
            case "south_jiangsu_area":
            case "anhui_area":
            case "south_anhui_area":
            case "zhejiang_area":
            case "jiangxi_area":
            case "fujian_area":
            case "guangdong_area":
            case "west_guangdong_area":
            case "guangxi_area":
            case "yun_gui_area":
            case "yun_gui_borderland_area":
            case "sichuan_area":
            case "chuannan_area":
            case "chuanbei_area":
            case "huguang_area":
            case "hunan_area":
            case "henan_area":
            case "north_henan_area":
            case "shanxi_area":
            case "shaanxi_area":
            case "gansu_area":
            case "west_gansu_area":
            case "minas_gerais_area":
            case "sao_paolo_area":
            case "rio_de_janeiro_area":
            case "bahia_area":
            case "pernambuco_area":
            case "ceara_area":
            case "sao_francisco_area":
            case "paraguay_area":
            case "bahia_blanca_area":
            case "southern_pampas_area":
            case "buenos_aires_area":
            case "jujuy_area":
            case "chaco_area":
            case "banda_oriental_area":
            case "guyana_area":
            case "upper_guyana_area":
            case "quito_area":
            case "venezuela_area":
            case "bogota_area":
            case "cordillera_occidental_area":
            case "antisuyu_area":
            case "kuntisuyu_area":
            case "peruan_coast":
            case "chimor_area":
            case "ucayali_area":
            case "cajamarca_area":
            case "huanuco_area":
            case "upper_peru":
            case "potosi_area":
            case "great_woods_area":
            case "iroquoisia_area":
            case "south_iroquoisia_area":
            case "susquehanna_area":
            case "carolinas_area":
            case "south_carolina_area":
            case "upper_american_georgia_area":
            case "north_florida_area":
            case "south_appalachia_area":
            case "west_florida_area":
            case "mississippi_area":
            case "choctaw_area":
            case "alabama_area":
            case "ohio_country_area":
            case "miami_river_area":
            case "illinois_country_area":
            case "mississippi_plain_area":
            case "lower_louisiana_area":
            case "upper_louisiana_area":
            case "central_plains_area":
            case "dakota_area":
            case "badlands_area":
            case "texas_area":
            case "columbia_river_area":
            case "salish_sea_area":
            case "interior_plateau_area":
            case "newfoundland_area":
            case "labrador_area":
            case "cote_nord_area":
            case "upper_canada_area":
            case "huronia_area":
            case "northeast_mexico_area":
            case "durango_area":
            case "chihuahua_area":
            case "pecos_area":
            case "rio_grande_area":
            case "new_mexico_area":
            case "apacheria_area":
            case "colorado_plateau_area":
            case "california_area":
            case "jalisco_area":
            case "nayarit_area":
            case "michoacan_area":
            case "tierra_caliente_area":
            case "gran_chichimeca_area":
            case "guanajuato_area":
            case "zacatecas_area":
            case "mexico_area":
            case "puebla_area":
            case "guerrero_area":
            case "oaxaca_area":
            case "mixteca_area":
            case "eastern_mexico_area":
            case "huasteca_area":
            case "chiapas_area":
            case "yucatan_area":
            case "east_yucatan_area":
            case "campeche_area":
            case "guatemala_area":
            case "guatemala_lowlands_area":
            case "honduras_area":
            case "nicaragua_area":
            case "cuba_area":
            case "east_cuba_area":
            case "hispaniola_area":
            case "dominica_area":
            case "greater_antilles_area":
            case "lucayan_area":
            case "leeward_islands_area":
            case "windward_islands_area":
            case "unit_templates":
            case "target_unit_id":
            case "t_from":
            case "t_to":
            case "change_price":
            case "nogoods":
            case "grain":
            case "wine":
            case "wool":
            case "cloth":
            case "fish":
            case "fur":
            case "salt":
            case "naval_supplies":
            case "copper":
            case "gold":
            case "iron":
            case "slaves":
            case "ivory":
            case "tea":
            case "chinaware":
            case "spices":
            case "coffee":
            case "cotton":
            case "sugar":
            case "tobacco":
            case "cocoa":
            case "silk":
            case "dyes":
            case "tropical_wood":
            case "livestock":
            case "incense":
            case "glass":
            case "paper":
            case "gems":
            case "coal":
            case "unknown":
            case "culture_group":
            case "rebel_faction":
            case "general":
            case "army":
            case "friend":
            case "great_powers":
            case "empire":
            case "old_emperor":
            case "celestial_empire":
            case "decree":
            case "trade_league":
            case "religions":
            case "noreligion":
            case "catholic":
            case "papacy":
            case "anglican":
            case "protestant":
            case "reformed":
            case "orthodox":
            case "coptic":
            case "sunni":
            case "shiite":
            case "ibadi":
            case "buddhism":
            case "vajrayana":
            case "mahayana":
            case "confucianism":
            case "shinto":
            case "hinduism":
            case "sikhism":
            case "animism":
            case "shamanism":
            case "totemism":
            case "inti":
            case "nahuatl":
            case "mesoamerican_religion":
            case "norse_pagan_reformed":
            case "tengri_pagan_reformed":
            case "jewish":
            case "zoroastrian":
            case "religion_instance_data":
            case "christian":
            case "muslim":
            case "relation":
            case "eastern":
            case "dharmic":
            case "pagan":
            case "jewish_group":
            case "zoroastrian_group":
            case "active_cardinals":
            case "cardinal":
            case "invest_in_cardinal":
            case "reformation_center":
            case "fired_events":
            case "pending_events":
            case "nahuatl_events.1": //Todo all events ids
            case "buildings":
            case "building_builders":
            case "history":
            case "advisor":
            case "discovery_dates2":
            case "discovery_religion_dates2":
            case "building_construction":
            case "diplomacy_construction":
            case "merchant_construction":
            case "spy_actions":
            case "latent_trade_goods":
                return DataType.OBJECT;

            case "speed":
            case "multiplayer_random_seed":
            case "multiplayer_random_count":
            case "unit_template_id":
            case "num_collectors":
            case "from":
            case "province":
            case "duration":
            case "target_merge_province":
            case "under_construction_queued":
            case "seed":
            case "rank":
            case "government_rank":
            case "reform_level":
            case "hre_leagues_status":
            case "hre_religion_status":
            case "amount_of_provinces":
            case "weighted_cardinal":
            case "location":
            case "province_id":
            case "dead_roc":
            case "random":
            case "any_target_province":
            case "skill":
            case "patrol":
            case "improve_count":
            case "winter":
            case "previous_winter":
            case "center_of_trade":
            case "builder":
            case "building":
            case "direction":
            case "fort_influencing":
            case "from_province":
            case "nationalism":
            case "native_ferocity":
            case "native_hostileness":
            case "original_total":
            case "to":
            case "to_province":
                return DataType.INT;

            case "next_age_progress":
            case "prosperity":
            case "total_military_power":
            case "average_military_power":
            case "current":
            case "local_value":
            case "outgoing":
            case "value_added_outgoing":
            case "retention":
            case "steer_power":
            case "total":
            case "p_pow":
            case "max":
            case "collector_power":
            case "pull_power":
            case "retain_power":
            case "highest_power":
            case "max_demand":
            case "val":
            case "prev":
            case "max_pow":
            case "add":
            case "province_power":
            case "power_fraction":
            case "money":
            case "already_sent":
            case "power":
            case "power_modifier":
            case "potential":
            case "potential_heir_religion":
            case "civil_war_progress":
            case "consort_dipVar":
            case "consort_milVar":
            case "new_ruler_culture":
            case "new_ruler_religion":
            case "other_advisor_religion":
            case "num_converted_religion":
            case "t_in":
            case "t_out":
            case "ship_power":
            case "pirate_hunt":
            case "privateer_mission":
            case "privateer_money":
            case "current_price":
            case "total_privateer_power":
            case "progress":
            case "imperial_influence":
            case "reform_desire":
            case "papal_investment":
            case "missionary_progress":
            case "max_speed":
            case "base_tax":
            case "base_production":
            case "base_manpower":
            case "trade_power":
            case "cost":
            case "devastation":
            case "extra_cost":
            case "garrison":
            case "local_autonomy":
            case "native_size":
            case "original_tax":
            case "hostile_core_creation_cost":
                return DataType.FLOAT;

            case "used_client_names":
            case "players_countries":
            case "top_power":
            case "top_provinces":
            case "potential_incidents":
            case "\"germanic\"":
            case "\"british\"":
            case "\"french\"":
            case "\"west_slavic\"":
            case "\"carpathian\"":
            case "\"baltic\"":
            case "\"maghrebi\"":
            case "\"iranian\"":
            case "\"altaic\"":
            case "\"malay\"":
            case "\"southeastasian_group\"":
            case "\"western_aryan\"":
            case "\"southern_african\"":
            case "\"great_lakes_group\"":
            case "\"african\"":
            case "\"cushitic\"":
            case "\"evenks\"":
            case "cores":
            case "claims":
            case "discovered_by":
                return DataType.LIST_STRING;

            case "setgameplayoptions":
            case "id_counters":
            case "institution_origin":
            case "possible_provinces":
            case "score_rank":
                return DataType.LINE_INT;

            case "institutions_penalties":
            case "trade_goods_size":
            case "top_power_values":
            case "top_provinces_values":
            case "tradegoods_total_produced":
                return DataType.LINE_FLOAT;

            case "production_leader_tag":
            case "dynamic_countries":
            case "electors":
            case "members":
            case "colony_claim":
                return DataType.LINE_STRING;

            case "has_trader":
            case "has_state_patriach":
            case "has_state_pasha":
            case "has_capital":
            case "trade_company_region":
            case "recalc_defection":
            case "imperial_ban_allowed":
            case "internal_hre_cb":
            case "hre_inheritable":
            case "allows_female_emperor":
            case "tbk":
            case "hre_religion":
            case "original_hre_religion":
            case "hre_heretic_religion":
            case "original_hre_heretic_religion":
            case "papacy_active":
            case "scope_is_valid":
            case "center_of_religion":
            case "hre":
            case "is_city":
            case "discover":
            case "hre_liberated":
            case "mothball_command":
            case "once":
            case "permanent":
            case "ub":
            case "user_changed_name":
                return DataType.BOOL;

            default:

                if (LOGGER.isDebugEnabled() && !BANNED_WORDS.contains(key)) {
                    LOGGER.debug("Unknown gamestate key: " + key);
                }

                return DataType.UNKNOWN; //If UNKNOWN, DataType.getType(value), mostly because a key can have multiple types (ex: value)
        }
    }
}
